// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVaDPpQn2BfLn4TmgmuPxs1xaaqymBoRE',
    appId: '1:676880288351:web:96395adba5de82d6b0e9ea',
    messagingSenderId: '676880288351',
    projectId: 'bloodhero-01',
    authDomain: 'bloodhero-01.firebaseapp.com',
    storageBucket: 'bloodhero-01.firebasestorage.app',
    measurementId: 'G-S8TTKNS8WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYG_fhffGcdVkwTxxRndRp25aIfbBFC3w',
    appId: '1:676880288351:android:02e073d3c27c59cab0e9ea',
    messagingSenderId: '676880288351',
    projectId: 'bloodhero-01',
    storageBucket: 'bloodhero-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOgWlex-QFAg4uP4JySyUH9A1bnEiwGig',
    appId: '1:676880288351:ios:9117148b98a730c6b0e9ea',
    messagingSenderId: '676880288351',
    projectId: 'bloodhero-01',
    storageBucket: 'bloodhero-01.firebasestorage.app',
    iosBundleId: 'com.example.bloodhero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOgWlex-QFAg4uP4JySyUH9A1bnEiwGig',
    appId: '1:676880288351:ios:9117148b98a730c6b0e9ea',
    messagingSenderId: '676880288351',
    projectId: 'bloodhero-01',
    storageBucket: 'bloodhero-01.firebasestorage.app',
    iosBundleId: 'com.example.bloodhero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVaDPpQn2BfLn4TmgmuPxs1xaaqymBoRE',
    appId: '1:676880288351:web:5628817a300d5dddb0e9ea',
    messagingSenderId: '676880288351',
    projectId: 'bloodhero-01',
    authDomain: 'bloodhero-01.firebaseapp.com',
    storageBucket: 'bloodhero-01.firebasestorage.app',
    measurementId: 'G-NXZSE8WDKS',
  );
}
